services:
  FRCNN2:
    image: frcnn2image
    volumes:
        - ./:/app
    ports:
        - "8888:8888"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
     
 
 
    